name: LOCI Analysis
on:
  push:
    branches:
      - loci/main-*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  loci:
    if: vars.UPSTREAM_REPO != ''
    runs-on: ubuntu-latest

    env:
      # @configure: Set your loci project name or keep it empty if project name is derived from repo name
      LOCI_PROJECT: 'OpenSSLMelisaTest-Mirror'
      LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
      LOCI_BACKEND_URL: '${{ vars.LOCI_BACKEND_URL }}'
      GH_TOKEN: ${{ secrets.MIRROR_REPOS_WRITE_PAT }}

    environment: 'production'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}

      - name: Compute target
        id: target
        if: github.event_name == 'push'
        run: |
          branch="${{ github.ref_name }}"
          sha="${branch#loci/main-}"
          echo "value=main@${sha}" >> "$GITHUB_OUTPUT"

      - name: Compute base
        id: base
        if: github.event_name == 'pull_request'
        run: |
          git remote add upstream "https://github.com/${{ vars.UPSTREAM_REPO }}.git" 2>/dev/null || true   
          git fetch upstream                                                                               
          upstream_default=$(gh api "repos/${{ vars.UPSTREAM_REPO }}" --jq .default_branch)                
          merge_base=$(git merge-base HEAD "upstream/${upstream_default}")                                 
          short_sha="${merge_base:0:7}"                                                                    
          echo "value=main@${short_sha}" >> "$GITHUB_OUTPUT"                                               

      # @configure: Install build dependencies for your project
      - name: Install dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu build-essential cmake git ninja-build python3-minimal
          echo "Cross compiler installed"
        shell: bash

      # @configure: Build your project binaries
      - name: Build
        run: |
          CC=gcc CXX=g++ ./Configure linux-aarch64 --cross-compile-prefix=aarch64-linux-gnu- -g -fno-stack-protector
          make -j
          mv apps/openssl openssl
          echo "Successfully compiled openssl"
        shell: bash

      - name: Upload
        uses: auroralabs-loci/loci-action@v1
        with:
          mode: upload
          # @configure: List your binary paths/directories/globs 
          binaries: |
                openssl
                libcrypto.so
                libcrypto.so.3
                libssl.so
                libssl.so.3
          project: '${{ env.LOCI_PROJECT }}'
          target: ${{ steps.target.outputs.value || ''}}
          base: ${{ steps.base.outputs.value || '' }}
